PATH=$HOME/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin

if [[ -d ~/Qt ]]; then
	PATH+=:$HOME/Qt/5.5/clang_64/bin
fi

HISTFILE=~/.zshrc_history
SAVEHIST=1000
HISTSIZE=1000

setopt inc_append_history
setopt share_history

if [[ -f ~/.myzshrc ]]; then
	source ~/.myzshrc
fi

USER=`/usr/bin/whoami`
GROUP=`/usr/bin/id -gn $user`
MAIL="$USER@student.42.fr"
export USER
export GROUP
export MAIL
